### ISSUE TITLE
安装拓展后功能无法使用，VSCode提示“command 'extension.beautifySql' not found”

### ISSUE THREAD

**Issue by hdefucom** [clarkyu2016/sql-beautify#18]
平台：Windows 10 x64  /  MacOS11.4
VSCode版本：Windows1.59.1  /  Mac1.58
插件版本：所有版本

安装拓展后功能无法使用，无论是右键菜单还是快捷键VSCode都提示“command 'extension.beautifySql' not found”。
VSCode DevelopTool控制台抛出异常：
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by clarkyu2016** [comment]
该问题确实会在部分用户中存在，非常奇怪🤣我现在也没法复原，暂时没有能力解决🤣感觉可能是。可以看下vscode具体信息吗？在帮助-关于那里。
我的信息是：
版本: 1.61.2 (user setup)
提交: 6cba118ac49a1b88332f312a8f67186f7f3c1643
日期: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by hdefucom** [comment]
我国庆重装升到win11了，还是存在这个问题
![image](https://user-images.githubusercontent.com/51500043/139607235-662aa556-56fa-437d-96c9-4d0c28eb17ba.png)

**Comment by hdefucom** [comment]
大概问题找到了，貌似是这几个拓展冲突了
Oracle Developer Tools for VS Code (SQL and PLSQL)
SQL Database Projects
SQL Server (mssql)

**Comment by hdefucom** [comment]
由于这几个拓展很久没用，之前忘记了

**Comment by clarkyu2016** [comment]
感谢你的反馈下次，我把这个补到说明上去！
