### ISSUE TITLE
格式化后影响字段名的大小写

### ISSUE THREAD

**Issue by ljfre** [clarkyu2016/sql-beautify#21]
关键词调为小写后，格式化时会把含有关键词的大写的字段名变为小写，如
格式前：group by  CUST_PHONE
格式后：group by  CUST_PHonE

**Comment by clarkyu2016** [comment]
近期会上个新的版本解决这个问题！

**Comment by clarkyu2016** [comment]
新的版本2.10.0已经解决小写问题，感谢您的反馈！
