### ISSUE TITLE
Extension 'SQL Beautify' is configured as formatter but it cannot format 'SQL'-files

### ISSUE THREAD

**Issue by ivaquero** [clarkyu2016/sql-beautify#22]
I set this ext in settings as `defaultFormatter`, but it cannot be identified.

```json
{
"[sql]": {
    "editor.defaultFormatter": "clarkyu.vscode-sql-beautify"
  },
}
```

![image](https://user-images.githubusercontent.com/46377665/148003966-57d15ea8-71f7-4ebd-90cb-e6cf05aaece9.png)

**Comment by clarkyu2016** [comment]
HI, Ivaquero. Thera are some unknown conflict between sql beautify and others.
If you still want to use sql beautify,
1.uninstall other plugins temporarily
2. delete cache for your vscode.

**Comment by ivaquero** [comment]
@clarkyu2016 Can this be solved by VS Code official devs?

**Comment by clarkyu2016** [comment]
> @clarkyu2016 Could you please ask help of VS Code official devs? Or I can do this.

Hi,ivaquero! Thanks for your solution, your pull request has been merged.

**Comment by clarkyu2016** [comment]
There is no need to set this ext in settings as defaultFormatter. The plugin only works in .sql files when you press specific commands (like "Shift+Alt+F").

**Comment by ivaquero** [comment]
Yeah, the ext pretty works well in files. I just think it could be more convenient as the `defaultFormatter`. 

Good works, thank you !

> I really wish that I know front-end programming 😅.
