### ISSUE TITLE
行尾备注，格式化后添加了空格且位置换行了

### ISSUE THREAD

**Issue by thx-god** [clarkyu2016/sql-beautify#29]
--原始代码
select  *
from tb1
where xx in ('AA', 'BB')  --测试备注1
      and yy in ( '18', '115', '14', '67', '36', '34', '31', '28', '45', '1000007', '1000015', '33', '131', '178', '29', '30', '185', '1000008', '220', '46', '47', '1000016', '1000053', '1000046', '66', '221')--测试备注2

--格式化一次后
select  *
from tb1
where xx in ('AA', 'BB')  -- 测试备注1
      and yy in ( '18', '115', '14', '67', '36', '34', '31', '28', '45', '1000007', '1000015', '33', '131', '178', '29', '30', '185', '1000008', '220', '46', '47', '1000016', '1000053', '1000046', '66', '221')
                          -- 测试备注2

--格式化两次后
select  *
from tb1
where xx in ('AA', 'BB')  --  测试备注1
      and yy in ( '18', '115', '14', '67', '36', '34', '31', '28', '45', '1000007', '1000015', '33', '131', '178', '29', '30', '185', '1000008', '220', '46', '47', '1000016', '1000053', '1000046', '66', '221')
-- 测试备注2

**Comment by clarkyu2016** [comment]
这个是由于转小写过程中新加的and缩进功能导致的，可以暂时开启自动转换为大写，避免出现该类问题。
修复中....

**Comment by clarkyu2016** [comment]
新的0.4.0版本已经修复这个问题，可以再试试~
