### ISSUE TITLE
【字段中带注释】BUG 部分场景下的SQL写法会导致格式化错误

### ISSUE THREAD

**Issue by aleegreat** [clarkyu2016/sql-beautify#3]
案例：
SELECT  nvl(a.xxx,' --'） -- comment 
    ,a.yyy
FROM a;

选中格式化成：
SELECT  nvl(a.xxx,' --'） -- comment ,a.yyy
FROM a;

应该是NVL 中的默认值 '--' 被识别成了注释。 

感谢修复~

**Comment by clarkyu2016** [comment]
感谢你提供的badcase ,带注释的字段确实是比较棘手的情况（因为大家会把注释加在任意部位）。您提到的这个问题会尝试在下个版本进行修复。

**Comment by clarkyu2016** [comment]
已经修复，请下载最新版使用
