### ISSUE TITLE
关系运算符空格分割

### ISSUE THREAD

**Issue by transposition** [clarkyu2016/sql-beautify#35]
最近新发现这个宝藏插件，大大缓解了我的强迫症，非常感谢
不过，我因为是使用Hive，关系运算符格式化后会中间添加空格，e.g.
a <= b 会变成 a < = b,  a != b  会变成  a ! = b 
这会导致hive执行报错，想问是否可以去掉中间的空格，我觉得<= 两边增加空格是会变漂亮，但强行把运算符拆开，反而语义上看起来不自然

**Comment by clarkyu2016** [comment]
> 最近新发现这个宝藏插件，大大缓解了我的强迫症，非常感谢 不过，我因为是使用Hive，关系运算符格式化后会中间添加空格，e.g. a <= b 会变成 a < = b, a != b 会变成 a ! = b 这会导致hive执行报错，想问是否可以去掉中间的空格，我觉得<= 两边增加空格是会变漂亮，但强行把运算符拆开，反而语义上看起来不自然

0.3.7版本已经修复这个问题了，升级试试，如果有问题欢迎随时和我反馈！
