### ISSUE TITLE
:= 会被添加空格导致失效

### ISSUE THREAD

**Issue by lpzzz** [clarkyu2016/sql-beautify#38]
感谢大佬的插件，本人主要用于MySQL，大部分时候都运作的非常完美
只是在SELECT语法中的临时变量赋值的时候
> @someVariable := 'someValue'

中间会被添加空格
> @someVariable : = 'someValue'

导致失效，不知道是否和HQL相关？是否可以修正这个空格？

**Comment by clarkyu2016** [comment]
新版本0.3.13已经修复，感谢您的反馈！
