### ISSUE TITLE
DDL中表名带有特定关键字时会出现错误

### ISSUE THREAD

**Issue by YouboFAN** [clarkyu2016/sql-beautify#39]
DDL建表语句 表名带有特定关键字时会出现格式化错误
原DDL

```
CREATE TABLE a.tmp_interact (
    `uid` bigint COMMENT "uid",
    `label` bigint COMMENT "标签"
) COMMENT "sample table" partitioned by (`pt` STRING);
```

格式化后出现问题

     CREATE  TABLE  COMMENT undefined
    ,`uid`   bigint COMMENT  "uid"
    ,`label` bigint COMMENT  "标签"

) COMMENT "sample table" PARTITIONED by (`pt` STRING);
将表名中的int替换成其他比如it，再格式化后正常

```
CREATE TABLE a.tmp_iteract (
     `uid`   bigint COMMENT  "uid"
    ,`label` bigint COMMENT  "标签"
) COMMENT "sample table" PARTITIONED by (`pt` STRING);
```

目前尝试了一下int、float都会引发此错误

**Comment by clarkyu2016** [comment]
新版本0.3.13已经修复，感谢您的反馈！

**Comment by xieying1995** [comment]
好像还有问题，如下所示，版本号是v0.3.15。


`CREATE TABLE if not exists tmp.sms_submit_info
    (
        `uid`            string  COMMENT  '用户id',
        `content`        string  COMMENT  '内容'
    ) comment "test"
        partitioned by (
            `data_date` bigint   COMMENT  '日期'
            )
        ROW FORMAT SERDE
            'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
        STORED AS INPUTFORMAT
            'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
            OUTPUTFORMAT
                'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'

-- 美化之后，直接吞行了。
CREATE TABLE if not exists tmp.sms_submit_info 
(
     `uid`       STRING COMMENT  '用户id'
    ,`content`   STRING COMMENT  '内容' 
    ,`data_date` BIGINT COMMENT  '日期' 
) 
ROW FORMAT SERDE 
'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat' 
`

目标应该是
`CREATE TABLE if not exists tmp.sms_submit_info
    (
        `uid`               string  COMMENT  '用户id',
        `content`        string  COMMENT  '内容'
    )   COMMENT 'test'
        PARTITIONED by (
         `data_date`   bigint   COMMENT  '日期'
    )
ROW FORMAT SERDE 
    'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
    'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
    'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat' 
`
