### ISSUE TITLE
Some problems while using SQL Beautify.

### ISSUE THREAD

**Issue by LiHaoyu1994** [clarkyu2016/sql-beautify#4]
I found that some problems while using it.
If you use it to format the code(hive sql), you will find these problems:
1. Some symbols such as ',' will lost.
2. Some table name will be seperate that would cause the table name cannot be found.

-----
[delete code for the sake of security]

**Comment by clarkyu2016** [comment]
Hi,LiHaoyu1994. there is a problem in 0.1.28 version when you have a commet symbol(--) in your code. 
Thanks for your feedback.
Please update the plugin to the lattest vervsion.
