### ISSUE TITLE
能不能加上也能识别.sh和.script后面文件

### ISSUE THREAD

**Issue by zhangyu345293721** [clarkyu2016/sql-beautify#41]
你好，我看着目前只能识别.sql和.hql后缀的文件，能不能加上能识别.sh和.script的文件呀，或者提供一个接口自己能配置也行

**Comment by clarkyu2016** [comment]
你好，如果需要在.sh和.script文件上格式化sql语句，可以在vscode编辑右下角选择语言模式，选择sql即可使用插件，同时也不会改变.sh后缀
接口的话，如果类似需求比较多的话会考虑开发的！
