### ISSUE TITLE
with语句中的注释问题

### ISSUE THREAD

**Issue by BryceQin** [clarkyu2016/sql-beautify#43]
格式化前：
WITH temp AS
(
    SELECT  t.rpt_prd
    FROM t
    GROUP BY  t.rpt_prd --临时表
), 
data1 as(
SELECT  t.rpt_prd
FROM t
GROUP BY  t.rpt_prd --临时表 
),
data2 as(
SELECT  t.rpt_prd
FROM t
GROUP BY  t.rpt_prd --临时表 
)
格式化后：
WITH temp AS
(
    SELECT  t.rpt_prd
    FROM t
    GROUP BY  t.rpt_prd --临时表
), data1 as(
SELECT  t.rpt_prd
FROM t
GROUP BY  t.rpt_prd --临时表 )
         ,data2 as(
SELECT  t.rpt_prd
FROM t
GROUP BY  t.rpt_prd --临时表 )
这里有两个问题：
1.data1和data2 as后的)被当做了注释的一部分，引起报错
2.with语句后如有多个代码块希望可以换行重新开始，比如这里现在是在)后紧接着开始新的代码块`), data1 as(`

**Comment by clarkyu2016** [comment]
> 格式化前： WITH temp AS ( SELECT t.rpt_prd FROM t GROUP BY t.rpt_prd --临时表 ), data1 as( SELECT t.rpt_prd FROM t GROUP BY t.rpt_prd --临时表 ), data2 as( SELECT t.rpt_prd FROM t GROUP BY t.rpt_prd --临时表 ) 格式化后： WITH temp AS ( SELECT t.rpt_prd FROM t GROUP BY t.rpt_prd --临时表 ), data1 as( SELECT t.rpt_prd FROM t GROUP BY t.rpt_prd --临时表 ) ,data2 as( SELECT t.rpt_prd FROM t GROUP BY t.rpt_prd --临时表 ) 这里有两个问题： 1.data1和data2 as后的)被当做了注释的一部分，引起报错 2.with语句后如有多个代码块希望可以换行重新开始，比如这里现在是在)后紧接着开始新的代码块`), data1 as(`

请不要这样写`as(`，插件目前无法识别，`as (` 就能保证正常运行

**Comment by BryceQin** [comment]
哈哈，自己写会注意，但是需要review 别人的代码，就很难保证，看看能不能也优化一下这里

**Comment by clarkyu2016** [comment]
> 哈哈，自己写会注意，但是需要review 别人的代码，就很难保证，看看能不能也优化一下这里

好的 这个点我记一下！
