### ISSUE TITLE
如何避免频繁的换行？

### ISSUE THREAD

**Issue by IBITM** [clarkyu2016/sql-beautify#6]
我的代码里面有很多 nvl 的判断逻辑
```   
nvl(
      today_table.some_field,
      yesterday_day.some_field
  ) as some_field
``` 
从代码可读性来说我更希望它是这样的
```
nvl(today_table.some_field, yesterday_day.some_field) as some_field
``` 
应该如何修改代码来实现这个功能呢？

**Comment by clarkyu2016** [comment]
可以发一份数据字段脱敏后的版本吗，方便我定位问题？
因为我自己测了下：
这是我的原始sql:

select a,nvl(today_table.some_field,yesterday_day.some_field) as some_field
test,a,b,c 
from table a

格式化后
SELECT  a
       ,nvl(today_table.some_field,yesterday_day.some_field) AS some_field test
       ,a
       ,b
       ,c
FROM TABLE a

**Comment by clarkyu2016** [comment]
> 我的代码里面有很多 nvl 的判断逻辑
> 
> ```
> nvl(
>       today_table.some_field,
>       yesterday_day.some_field
>   ) as some_field
> ```
> 
> 从代码可读性来说我更希望它是这样的
> 
> ```
> nvl(today_table.some_field, yesterday_day.some_field) as some_field
> ```
> 
> 应该如何修改代码来实现这个功能呢？

可以发一份数据字段脱敏后的版本吗，方便我定位问题？
因为我自己测了下：
这是我的原始sql:

select a,nvl(today_table.some_field,yesterday_day.some_field) as some_field
test,a,b,c
from table a

格式化后
SELECT a
,nvl(today_table.some_field,yesterday_day.some_field) AS some_field test
,a
,b
,c
FROM TABLE a

**Comment by IBITM** [comment]
> > 我的代码里面有很多 nvl 的判断逻辑
> > ```
> > nvl(
> >       today_table.some_field,
> >       yesterday_day.some_field
> >   ) as some_field
> > ```
> > 
> > 
> > 从代码可读性来说我更希望它是这样的
> > ```
> > nvl(today_table.some_field, yesterday_day.some_field) as some_field
> > ```
> > 
> > 
> > 应该如何修改代码来实现这个功能呢？
> 
> @IBITM 可以发一份数据字段脱敏后的版本吗，方便我定位问题？
> 因为我自己测了下：
> 这是我的原始sql:
> 
> select a,nvl(today_table.some_field,yesterday_day.some_field) as some_field
> test,a,b,c
> from table a
> 
> 格式化后
> SELECT a
> ,nvl(today_table.some_field,yesterday_day.some_field) AS some_field test
> ,a
> ,b
> ,c
> FROM TABLE a

可以尝试一下这个版本，之前的样例应该是字段名太短了，没有触发换行的逻辑，谢谢
```
select
    a,
    nvl(today_table.some_field_with_tooooo_may_character, yesterday_day.some_field_with_tooooo_may_character) as some_field_with_tooooo_may_character test,
    a,
    b,
    c
from
    table a
```

**Comment by clarkyu2016** [comment]
@IBITM你提供的这段代码我格式化后看起来也比较正常
select
    a,
![微信截图_20210506165056](https://user-images.githubusercontent.com/17335659/117270741-1bcce780-ae8c-11eb-9a6c-02f2d0d14474.png)

    nvl(today_table.some_field_with_tooooo_may_character, yesterday_day.some_field_with_tooooo_may_character) as some_field_with_tooooo_may_character test,
    a,
    b,
    c
from
    table a

不太清楚具体的原因，如果方便的话可以加下我的wechat: clarkmanutd，具体再研究下是什么问题

**Comment by IBITM** [comment]
我大概已经定位问题了，我应该安装了多种 format 工具，在格式化 SQL 的时候出现了冲突，现在屏蔽了其他的 format 工具，已经可以了，非常感谢帮助
