### ISSUE TITLE
GROUP BY和ORDER BY的对齐问题

### ISSUE THREAD

**Issue by NicestAsperger** [clarkyu2016/sql-beautify#63]
格式化后GROUP BY和ORDER BY语句距离后文的空格数不同导致无法对齐，见图。

<img width="230" alt="image" src="https://github.com/clarkyu2016/sql-beautify/assets/105861182/7fd67e08-a80c-4a62-b525-54c99bd05c27">

环境：VS Code（MacBook Pro intel）

**Comment by clarkyu2016** [comment]
v0.3.23 修复了这几个问题
