### ISSUE TITLE
[IMP] can you add a option for putting the comma at the end of a line? :)

### ISSUE THREAD

**Issue by RRRoger** [clarkyu2016/sql-beautify#7]
- version number: v0.1.29
- IMPROVEMENT: add a option for putting the comma at the end of a line

```sql
SELECT  name
       ,phone
       ,email
FROM user
```

### What I want

```sql
SELECT  name,
        phone,
        email
FROM user
```

**Comment by clarkyu2016** [comment]
Please try new version v0.1.30
and if there is any problem, please tell me.
@RRRoger

**Comment by RRRoger** [comment]
It helps me a lot, thanks for your support and recommendation. 😃
