### ISSUE TITLE
怎么将格式化中tab使用两个空格代替？

### ISSUE THREAD

**Issue by taoistwar** [clarkyu2016/sql-beautify#9]
Tab直接复制到Hive Cli中会出现问题，每次格式化后复制都得手工替换下

**Comment by clarkyu2016** [comment]
在vscode设置-首选项-扩展 就能看到sql beautify的选项，有个替换开启选项

**Comment by clarkyu2016** [comment]
![Uploading tablevswhitespace.png…]()

**Comment by clarkyu2016** [comment]
![tablevswhitespace](https://user-images.githubusercontent.com/17335659/123601962-d7761c00-d82a-11eb-8795-270415911d1e.png)

在vscode设置-首选项-扩展 就能看到sql beautify的选项，有个替换开启选项
